### ISSUE TITLE
Downloading package dependencies at install time is not ideal

### ISSUE THREAD

**Issue by platy** [heartsucker/node-deb#17]
I see that you moved the running of `npm install` from package time to install time. (Thanks for the warnings - no time was wasted) I understand the reason this was done but it causes some new problems. Both options for `npm install` are bad:

- package time - if any modules are platform dependent they will be built incorrectly.
- install time - some dependencies may not be available or may download different versions.

I haven't tried this, but I think the solution is to `npm install` at packaging time and then just do an `npm rebuild` at install time.

**Comment by ehartsuyker** [comment]
Yeah, that's why I was having it auto include the `npm-shrinkwrap.json` if it exists. At this point I'm inclined to think that the best thing is to do is let it do a different `npm install` every time you install the package to get updated packages. If someone wanted nailed down versions, they'd shrinkwrap it (right?).

However, being just on the ops side of the `node` stuff, there's a good chance I'm wrong. Let's talk next time I'm in the office (or post it here to let other people join the discussion). I mean, I guess I want to really understand *why* before I make the change, y'know?

**Comment by heartsucker** [comment]
Fixed in version 0.1.11.
