### ISSUE TITLE
File ownership issues

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/node-deb#18]
First reported by @empierre on issue #16. New ticket for organization.

---------------------

also had issues of npm unpak issues, had to add this to correct the issue (clean cache and install as an unprivillegied user:

preinst:
npm cache clean

postint:
chown 'www-data:www-data' '/var/www/'
chown -R 'www-data:www-data' '/usr/share/mydomoathome'

npm_install() {
cd "/usr/share/$1/app"
if [ -e 'node_modules' ]; then
rm -rf 'node_modules'
fi
sudo -u www-data npm install --production
}

**Comment by empierre** [comment]
another remark, if installing as a user, its how directory must be writable by npm:

if ! [ -d '/var/www' ]; then
  mkdir -p '/var/www'
fi

**Comment by heartsucker** [comment]
@empierre I'm finally getting around to looking at this, and I don't think I understand what the file issues are here. It looks like you're using a custom `postinst` script to put things into `/var/www`, so I don't think I can help you here. I did a release with a number of changes since this was reported.

So can I get you to:
- Try it again with the latest version of `node-deb`
- Report back you whole `package.json` and command line args and templates so I can see what may have gone wrong

**Comment by empierre** [comment]
@heartsucker I wanted to use www-data user already existing, maybe not a good idea since its home does not belong to him...

I have merged with your code but had to keep the old way in case the node_modules was missing (migration issue for packages existing prior to node_modules embedded in the package.

npm_install() {
  cd "/usr/share/$1/app"
  sudo npm config set loglevel warn
  if [ -e 'node_modules' ]; then
      sudo -u www-data npm rebuild
  else
      sudo -u www-data npm install --production    
  fi
  #sudo -u www-data npm config set loglevel warn
}

**Comment by heartsucker** [comment]
@empierre The error with node_modules went unnoticed and will be fixed in the next release. If you're using an existing user and file ownership issues happen, I think that's outside the scope of this tool. I think manually setting your templates is a sufficient workaround

I'm going to close this. If you feel like this issues was inadequately addressed, I can reopen it.
