### ISSUE TITLE
Spurious error printout

### ISSUE THREAD

**Issue by vidstige** [heartsucker/node-deb#32]
I'm getting a spurios error printout whe installing my package using `dpkg --install myapp_0.3.15_all.deb`

See below

```
(Reading database ... 178426 files and directories currently installed.)
Preparing to unpack myapp_0.3.15_all.deb ...
Removed symlink /etc/systemd/system/multi-user.target.wants/myapp.service.
Failed to stop myapp.service\x7d.service: Unit myapp.service\x7d.service not loaded.
myapp wasn't even running!
Unpacking myapp (0.3.15) over (0.3.14) ...
Setting up myapp (0.3.15) ...
Directory 'node_modules' exists. Running 'npm rebuild'

> websocket@1.0.24 install /usr/share/myapp/app/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied
minimist@1.2.0 /usr/share/myapp/app/node_modules/minimist
websocket@1.0.24 /usr/share/myapp/app/node_modules/websocket
debug@2.6.1 /usr/share/myapp/app/node_modules/websocket/node_modules/debug
ms@0.7.2 /usr/share/myapp/app/node_modules/websocket/node_modules/debug/node_modules/ms
nan@2.5.1 /usr/share/myapp/app/node_modules/websocket/node_modules/nan
typedarray-to-buffer@3.1.2 /usr/share/myapp/app/node_modules/websocket/node_modules/typedarray-to-buffer
is-typedarray@1.0.0 /usr/share/myapp/app/node_modules/websocket/node_modules/typedarray-to-buffer/node_modules/is-typedarray
yaeti@0.0.6 /usr/share/myapp/app/node_modules/websocket/node_modules/yaeti
node-deb@0.5.0 /usr/share/myapp/app/node_modules/node-deb
Created symlink from /etc/systemd/system/multi-user.target.wants/myapp.service to /etc/systemd/system/myapp.service.
```

Note the `sh: 1: cannot create builderror.log: Permission denied`. What is it trying to build? Why can't it write to the log, etc. Everything seems to work fine in spite of this error message. Normally I try to build things so that no errors are emitted when everything works as expected. Please advice.

**Comment by heartsucker** [comment]
When you do a `dpkg --install`, it runs the pre-packaged Debian maintainer scripts you can find in the directory `templates`.  In this case, the [postrm](https://github.com/heartsucker/node-deb/blob/develop/templates/postinst#L71-L82) script runs either `npm rebuild --production` (as in your example) or `npm install --production`. The `node-gyp` tool is building the native extensions from your dependency `websocket` (or so it appears).

So this error.

```
sh: 1: cannot create builderror.log: Permission denied
```

Comes from a third party tool. I'm not sure why there's a permission denied since you're running this as `root`.

I'm making this a closed since I'm fairly sure it's not an issue with `node-deb` itself, but i you have evidence to the contrary, feel free to reopen it.
